### PR TITLE
Added goodjson support for DynamicDocument

### PR DESCRIPTION
**Pull request by pysoserious**

### CODE REVIEW

**Comment by hiroaki-yamamoto** [comment]
Do you mind if I ask you to explain what this pull request is, what did you make changes on this pull request, and why this pull request needs to be merged?

**Comment by pysoserious** [comment]
> Do you mind if I ask you to explain what this pull request is, what did you make changes on this pull request, and why this pull request needs to be merged?

The to_json() method was not working on DynamicDocument. It was only working for Document and EmbeddedDocument.
I have added the support for DynamicDocument and it is working fine.

**Comment by hiroaki-yamamoto** [comment]
Ok, thank you for the clarification, but how do you prove that it's working? As far as I review your code, there's no test-code for `DynamicDocument`.

**Comment by pysoserious** [comment]
> Ok, thank you for the clarification, but how do you prove that it's working? As far as I review your code, there's no test-code for `DynamicDocument`.

Yes, I had not added test cases.
Can you urgently merge this pull request. We are deploying with your package.
I will raise another pull request with test code.

**Comment by hiroaki-yamamoto** [comment]
https://mongoengine-goodjson.readthedocs.io/en/latest/contribution.html#pull-request

> * Test code is mandatory. Your bug must be reproducible, and writing test code is showing the proof of the bug. Any pull requests that don’t have test code might be rejected.

**Comment by hiroaki-yamamoto** [comment]
Unfortunately, this PR is rejected because of the lack of the test.

**Pull request closed without merging**
